### ISSUE TITLE
Can't tell what SHA was released in `emp releases`

### ISSUE THREAD

**Issue by nyergler** [remind101/emp#10]
When looking at the release list, it shows `remind101/r101-postoffice:master` as the release version. This isn't very useful in identifying what was actually released in that version. Showing the SHA would be much more informative.

![screen shot 2015-06-26 at 10 22 12 am](https://cloud.githubusercontent.com/assets/510875/8383217/4d4ed008-1bed-11e5-90a5-8dd5e3067503.png)

**Comment by ejholmes** [comment]
`emp deploy` just uses the primitive `/deploys` API of Empire, which can take a tag or a sha256 digest. Empire itself has no knowledge about what git sha `master` currently is. In this case, the `master` tag of the remind101/r101-postoffice repo was deployed. Deploying a mutable tag like `master` or `latest` is actually somewhat dangerous right now because we're [not resolving the tag to a sha256 digest](https://github.com/remind101/empire/issues/247).

Internally, that's why we use the separate `deploy` CLI, which uses the GitHub deployments API to resolve the `master` ref to a git sha, then deploy the docker image tagged with that commit sha.

There's definitely some room for confusion here, so it would be nice if it were possible to disable `emp deploy` if you only wanted to trigger deployments from GitHub webhooks.

**Comment by nyergler** [comment]
So is the solution to:

1. Make it possible to disable `emp deploy`, or
2. Make `emp deploy` use GH deployments if configured, or 
3. Make `emp deploy` resolve the tag to a SHA.

Or maybe some combination of the above?

Having two ways of doing things that have different results seems engineer-unfriendly at best, and dangerous at worst. I'd love to figure out how to make this more clear to other engineers.

**Comment by ejholmes** [comment]
My feeling is that no. 1 is the best. I think it should be a flag in empire to disable the `/deploys` endpoint and only allow deployments via github webhooks. I created an issue for this over here https://github.com/remind101/empire/issues/561.

**Comment by bmarini** [comment]
Or possibly have the deploys endpoint reject a deploy if it isn't a SHA
